module load tools
module load anaconda2/4.4.0
module load jdk/13.0.1
module load openjdk/13.0.1
module load java/1.8.0
module load jre/1.8.0

source activate fusioncatcher

DATA_DIR="/home/projects/cu_10160/people/ricmic/data"
OUTPUT_DIR="/home/projects/cu_10160/people/ricmic/output/"
FASTQ_FILES="${DATA_DIR}/synth/*/data.broadinstitute.org/Trinity/CTAT_FUSIONTRANS_BENCHMARKING/on_simulated_data/*/reads/*/"
# FusionCatcher needs its own source directory generated by 'fusioncatcher-build'
REF_DIR="${DATA_DIR}/ref/catcher_data/human_v98/"


function run_catcher() {
    fusioncatcher.py -d ${REF_DIR} -i ${sample} -o ${SAMPLE_OUTPUT_DIR} --threads=4
}

for sample in ${FASTQ_FILES}; do

    BASENAME=$(basename ${sample})
    SAMPLE_OUTPUT_DIR=${OUTPUT_DIR}/${BASENAME}/fusion_catcher
    # check if output directory exists and create
    if [[ ! -d ${SAMPLE_OUTPUT_DIR} ]]; then
	echo "creating dir ${SAMPLE_OUTPUT_DIR}"
	mkdir ${SAMPLE_OUTPUT_DIR}
    fi
    
        echo "Running FusionCatcher on ${BASENAME}..."
        
        run_catcher
    done
done

exit 0



