module load tools
module load anaconda3/4.4.0

source activate fusionbloom

DATA_DIR="/home/projects/cu_10160/people/ricmic/data"
OUTPUT_DIR="/home/projects/cu_10160/people/ricmic/output/"
LEFT_FILES="${DATA_DIR}/synth/*/data.broadinstitute.org/Trinity/CTAT_FUSIONTRANS_BENCHMARKING/on_simulated_data/*/reads/*_1.fq*"
RIGHT_FILES="${DATA_DIR}/synth/*/data.broadinstqitute.org/Trinity/CTAT_FUSIONTRANS_BENCHMARKING/on_simulated_data/*/reads/*_2.fq*"
# FusionCatcher needs its own source directory generated by 'fusioncatcher-build'
REF_DIR="${DATA_DIR}/ref/catcher_data/human_v98/"


function run_bloom() {
    
}

for left in ${LEFT_FILES}; do
   for right in ${RIGHT_FILES}; do
      if [[ ${left%_*} == ${right%_*} ]]; then
        BASENAME=$(basename ${left})
        SAMPLE_OUTPUT_DIR=${OUTPUT_DIR}/${BASENAME%_*}/fusion_catcher
        # check if output directory exists and create
         if [[ ! -d ${SAMPLE_OUTPUT_DIR} ]]; then
                echo "creating dir ${SAMPLE_OUTPUT_DIR}"
                mkdir ${SAMPLE_OUTPUT_DIR}
         fi
	 
         
         echo "Running FusionCatcher on ${BASENAME}..."
         echo "With ${FASTQ_FILES}"
         
         run_bloom
      fi
   done
done

exit 0
