 
module load tools
module load anaconda2/4.4.0
module load jdk/13.0.1
module load openjdk/13.0.1
module load java/1.8.0
module load jre/1.8.0
module load fusioncatcher/1.20
module load bowtie/1.2.1.1
module load bowtie2/2.3.4.1
module load seqtk/1.3
module load bbmap/38.35

DATA_DIR="/home/projects/cu_10160/people/ricmic/data"
OUTPUT_DIR="/home/projects/cu_10160/people/ricmic/output/"
LEFT_FILES="${DATA_DIR}/synth/*/data.broadinstitute.org/Trinity/CTAT_FUSIONTRANS_BENCHMARKING/on_simulated_data/*/reads/*_1.fq*"
RIGHT_FILES="${DATA_DIR}/synth/*/data.broadinstqitute.org/Trinity/CTAT_FUSIONTRANS_BENCHMARKING/on_simulated_data/*/reads/*_2.fq*"
# FusionCatcher needs its own source directory generated by 'fusioncatcher-build'
REF_DIR="${DATA_DIR}/ref/catcher_data/"

# FUSIONCATCHER RELIES ON PYTHON2

function run_catcher() {
    fusioncatcher -d ${REF_DIR} -i ${FASTQ_FILES} -o ${SAMPLE_OUTPUT_DIR} --threads=4
}

for left in ${LEFT_FILES}; do
   for right in ${RIGHT_FILES}; do
      if [[ ${left%_*} == ${right%_*} ]]; then
        BASENAME=$(basename ${left})
        SAMPLE_OUTPUT_DIR=${OUTPUT_DIR}/${BASENAME%_*}/fusion_catcher
        # check if output directory exists and create
         if [[ ! -d ${SAMPLE_OUTPUT_DIR} ]]; then
                echo "creating dir ${SAMPLE_OUTPUT_DIR}"
                mkdir ${SAMPLE_OUTPUT_DIR}
         fi
         # Fusioncatcher also takes single FASTQ files to read
         FASTQ_FILES="${left},${right}"
         
         echo "Running FusionCatcher on ${BASENMAE}..."
         echo "With ${FASTQ_FILES}"
         
         fusioncatcher
      fi
   done
done

exit 0



